import './style.css';
import { supabase, supabaseEnabled } from './supabase.js';
import { parseCsv, detectMapping, normalizeTransactions, validateTransactions } from './csv.js';
import { getImportHistory, saveImport, removeImport, clearImports } from './importStore.js';

const app = document.querySelector('#app');
const money = new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});
const dateFmt = new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'});
const companies=[{id:'atlas',name:'Atlas AI Demo Company',plan:'Professional',role:'Owner'},{id:'arclight',name:'ArcLight Customer Trial',plan:'Enterprise Trial',role:'Admin'}];
const state={user:JSON.parse(localStorage.getItem('atlas-user')||'null'),company:localStorage.getItem('atlas-company')||'atlas',view:'imports',step:1,file:null,raw:null,mapping:{},validation:null};

function toast(message){const el=document.querySelector('#toast');if(!el)return;el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function initials(name){return name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function loginDemo(){state.user={name:'Brian Hess',email:'founder@atlasaiusa.com',role:'Owner'};localStorage.setItem('atlas-user',JSON.stringify(state.user));renderApp()}

function authScreen(){app.innerHTML=`<main class="auth-shell"><section class="auth-brand-panel"><div class="brand-lockup"><span class="brand-mark">A</span><div><strong>ATLAS AI</strong><small>SMARTLEDGER</small></div></div><div class="auth-copy"><span class="eyebrow">SPRINT 11A · FINANCIAL DATA HUB</span><h1>Bring financial data into focus.</h1><p>Upload a statement, verify every column, and prepare clean transactions for Atlas intelligence.</p><div class="auth-proof"><span>✓ Local CSV processing</span><span>✓ Validation before import</span><span>✓ Import history and rollback</span></div></div><small class="legal">© 2026 Atlas AI, LLC</small></section><section class="auth-form-panel"><div class="auth-card"><span class="status-chip">Sprint 11A</span><h2>Financial Import Center</h2><p>Enter the working demo to test CSV upload, automatic mapping, validation, preview, and import history.</p><button id="demoLogin" class="primary-button">Enter Sprint 11A demo</button><small class="configuration">${supabaseEnabled?'● Supabase connected':'● Demo mode · CSV files stay in this browser'}</small></div></section></main>`;document.querySelector('#demoLogin').onclick=loginDemo}

function navItem(view,icon,label){return `<button class="nav-item ${state.view===view?'active':''}" data-view="${view}"><span>${icon}</span>${label}</button>`}
function renderApp(){const company=companies.find(c=>c.id===state.company)||companies[0];app.innerHTML=`<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand-lockup sidebar-brand"><span class="brand-mark">A</span><div><strong>ATLAS AI</strong><small>SMARTLEDGER</small></div></div><nav class="side-nav">${navItem('dashboard','⌂','Dashboard')}${navItem('imports','⇧','Financial Imports')}${navItem('transactions','≡','Transactions')}${navItem('history','◷','Import History')}${navItem('settings','⚙','Settings')}</nav><div class="security-card"><span>◈</span><div><strong>Private processing</strong><small>Files remain in your browser</small></div></div><button id="logout" class="logout">↪ Sign out</button></aside><main class="main-area"><header class="topbar"><button class="menu" id="menu">☰</button><div class="company-select-wrap"><small>CURRENT WORKSPACE</small><select id="companySelect">${companies.map(c=>`<option value="${c.id}" ${c.id===company.id?'selected':''}>${c.name}</option>`).join('')}</select></div><div class="top-actions"><span class="sprint-chip">SPRINT 11A</span><div class="user-chip"><span>${initials(state.user.name)}</span><div><strong>${state.user.name}</strong><small>${company.role}</small></div></div></div></header><section id="content"></section></main></div><div id="toast" class="toast"></div>`;bindShell();renderView()}
function bindShell(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;renderApp()});document.querySelector('#companySelect').onchange=e=>{state.company=e.target.value;localStorage.setItem('atlas-company',state.company)};document.querySelector('#logout').onclick=async()=>{if(supabaseEnabled)await supabase.auth.signOut();localStorage.removeItem('atlas-user');state.user=null;authScreen()};document.querySelector('#menu').onclick=()=>document.querySelector('#sidebar').classList.toggle('open')}
function header(k,t,p){return `<div class="page-header"><div><span class="eyebrow">${k}</span><h1>${t}</h1><p>${p}</p></div><span class="plan-chip">Financial Data Hub</span></div>`}
function renderView(){const content=document.querySelector('#content');const views={dashboard,imports,transactions,history,settings};content.innerHTML=views[state.view]();bindView()}

function dashboard(){const h=getImportHistory();const total=h.reduce((s,x)=>s+x.rows,0);return `${header('SMARTLEDGER COMMAND CENTER','Financial data is ready for intelligence.','Sprint 11A creates the clean import foundation for categorization, savings detection, and forecasting.')}<div class="metrics"><article><small>TRANSACTIONS IMPORTED</small><strong>${total.toLocaleString()}</strong><span>${h.length} completed imports</span></article><article><small>LAST IMPORT</small><strong>${h[0]?dateFmt.format(new Date(h[0].createdAt)):'None'}</strong><span>${h[0]?.filename||'Upload your first CSV'}</span></article><article><small>VALIDATION RATE</small><strong>${h[0]?h[0].validRate+'%':'—'}</strong><span>Checked before every import</span></article><article><small>DATA STATUS</small><strong class="secure-text">Protected</strong><span>Processed locally in demo mode</span></article></div><div class="dashboard-grid"><article class="panel"><small>NEXT ACTION</small><h2>Import a bank or card statement</h2><p class="muted">SmartLedger will identify columns, normalize dates and amounts, flag incomplete rows, and preview the result before anything is saved.</p><button class="primary-button fit" data-action="new-import">Start CSV import</button></article><article class="panel readiness"><small>SPRINT 11A COMPLETION</small><div class="ring"><strong>100%</strong><span>BUILD READY</span></div><ul><li class="done">CSV parser</li><li class="done">Automatic mapping</li><li class="done">Validation and duplicates</li><li class="done">Import history</li></ul></article></div>`}

function imports(){return `${header('FINANCIAL IMPORT CENTER','Import financial transactions','Upload, map, validate, preview, and save a CSV statement in five guided steps.')}<div class="stepper">${['Upload','Map columns','Validate','Preview','Complete'].map((x,i)=>`<div class="step ${state.step===i+1?'active':''} ${state.step>i+1?'done':''}"><span>${state.step>i+1?'✓':i+1}</span><b>${x}</b></div>`).join('')}</div><article class="panel import-panel">${importStep()}</article>`}
function importStep(){if(state.step===1)return `<div class="import-intro"><span class="upload-icon">⇧</span><h2>Upload a CSV statement</h2><p>Use a transaction export from your bank, credit card, or accounting system.</p><label class="drop-zone" id="dropZone"><input id="fileInput" type="file" accept=".csv,text/csv"><strong>Drop CSV file here</strong><span>or click to browse</span><small>Maximum recommended size: 10 MB</small></label><button class="demo-button sample-button" data-action="sample">Use included sample data</button></div>`;
if(state.step===2)return `<div class="mapping"><div class="panel-heading"><div><small>FILE</small><h2>${state.file?.name||'sample-transactions.csv'}</h2></div><span class="row-chip">${state.raw.rows.length} rows detected</span></div><p class="muted">Confirm which source column belongs to each SmartLedger field.</p><div class="mapping-grid">${[['date','Transaction date',true],['vendor','Vendor / merchant',false],['description','Description',true],['amount','Debit / amount',true],['credit','Credit / deposit',false],['category','Category',false],['balance','Balance',false]].map(([key,label,required])=>`<label>${label}${required?' *':''}<select data-map="${key}"><option value="">Not mapped</option>${state.raw.headers.map(h=>`<option value="${h}" ${state.mapping[key]===h?'selected':''}>${h}</option>`).join('')}</select></label>`).join('')}</div><div class="wizard-actions"><button class="demo-button fit" data-action="back">Back</button><button class="primary-button fit" data-action="validate">Validate transactions</button></div></div>`;
if(state.step===3){const s=state.validation.summary;return `<div><div class="validation-hero ${s.invalid?'warning':'success'}"><span>${s.invalid?'!':'✓'}</span><div><h2>${s.invalid?'Review recommended':'Validation passed'}</h2><p>${s.valid} of ${s.total} rows are ready to import.</p></div></div><div class="validation-grid"><article><small>TOTAL ROWS</small><strong>${s.total}</strong></article><article><small>VALID</small><strong>${s.valid}</strong></article><article><small>NEEDS REVIEW</small><strong>${s.invalid}</strong></article><article><small>POSSIBLE DUPLICATES</small><strong>${s.duplicates}</strong></article><article><small>DEBITS</small><strong>${money.format(s.debits)}</strong></article><article><small>CREDITS</small><strong>${money.format(s.credits)}</strong></article></div><div class="wizard-actions"><button class="demo-button fit" data-action="back">Back</button><button class="primary-button fit" data-action="preview">Preview import</button></div></div>`}
if(state.step===4)return `<div><div class="panel-heading"><div><small>TRANSACTION PREVIEW</small><h2>Confirm before import</h2></div><span class="row-chip">Showing first 12 rows</span></div>${transactionTable(state.validation.rows.slice(0,12))}<div class="wizard-actions"><button class="demo-button fit" data-action="back">Back</button><button class="primary-button fit" data-action="commit">Import ${state.validation.summary.valid} transactions</button></div></div>`;
return `<div class="completion"><span>✓</span><h2>Import complete</h2><p>${state.validation.summary.valid} transactions are now available to SmartLedger.</p><div class="completion-card"><small>WHAT HAPPENS NEXT</small><strong>Sprint 11B will categorize transactions, normalize vendors, and detect duplicate payments.</strong></div><button class="primary-button fit" data-action="another">Import another CSV</button><button class="demo-button fit" data-action="view-history">View import history</button></div>`}

function transactionTable(rows){return `<div class="table-wrap"><table><thead><tr><th>Status</th><th>Date</th><th>Vendor</th><th>Description</th><th>Amount</th><th>Category</th></tr></thead><tbody>${rows.map(tx=>`<tr><td><span class="status-dot ${tx.valid?'ok':'bad'}"></span>${tx.duplicate?'Duplicate?':tx.valid?'Ready':'Review'}</td><td>${tx.date||tx.dateRaw||'—'}</td><td>${tx.vendor}</td><td>${tx.description}</td><td class="amount ${tx.amount>=0?'credit':'debit'}">${money.format(tx.amount)}</td><td>${tx.category}</td></tr>`).join('')}</tbody></table></div>`}
function transactions(){const tx=JSON.parse(localStorage.getItem('atlas-transactions')||'[]');return `${header('TRANSACTIONS','Imported transaction ledger','Review the latest transactions stored by the Financial Import Center.')}<article class="panel">${tx.length?transactionTable(tx.slice(0,100)):`<div class="empty"><h2>No transactions yet</h2><p>Complete a CSV import to populate this ledger.</p><button class="primary-button fit" data-action="new-import">Start import</button></div>`}</article>`}
function history(){const h=getImportHistory();return `${header('IMPORT HISTORY','Every import, clearly documented','Review source files, quality results, and completed transaction counts.')}<article class="panel"><div class="panel-heading"><div><small>AUDIT TRAIL</small><h2>${h.length} completed imports</h2></div>${h.length?'<button class="text-button" data-action="clear">Clear demo history</button>':''}</div>${h.length?`<div class="history-list">${h.map(x=>`<div><span class="file-badge">CSV</span><div><strong>${x.filename}</strong><small>${dateFmt.format(new Date(x.createdAt))} · ${x.rows} transactions · ${x.validRate}% valid</small></div><b>${money.format(x.debits)} debits</b><button class="icon-button" data-remove="${x.id}" title="Remove record">×</button></div>`).join('')}</div>`:`<div class="empty"><h2>No imports recorded</h2><p>Your completed CSV imports will appear here.</p></div>`}</article>`}
function settings(){return `${header('IMPORT SETTINGS','Financial data preferences','Configure safe defaults for future SmartLedger imports.')}<article class="panel form-grid"><label>Default currency<select><option>USD — US Dollar</option></select></label><label>Date format<select><option>Automatic detection</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></label><label class="toggle-row wide"><div><strong>Duplicate detection</strong><small>Flag matching date, vendor, and amount combinations.</small></div><input type="checkbox" checked></label><label class="toggle-row wide"><div><strong>Skip invalid rows</strong><small>Only import transactions that pass validation.</small></div><input type="checkbox" checked></label><button class="primary-button fit" data-action="save">Save settings</button></article>`}

function bindView(){document.querySelectorAll('[data-action]').forEach(btn=>btn.onclick=()=>action(btn.dataset.action));document.querySelectorAll('[data-remove]').forEach(btn=>btn.onclick=()=>{removeImport(btn.dataset.remove);renderApp();toast('Import record removed')});document.querySelectorAll('[data-map]').forEach(sel=>sel.onchange=e=>state.mapping[e.target.dataset.map]=e.target.value);const input=document.querySelector('#fileInput');if(input)input.onchange=e=>loadFile(e.target.files[0]);const drop=document.querySelector('#dropZone');if(drop){['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]))}}
async function loadFile(file){if(!file)return;if(!file.name.toLowerCase().endsWith('.csv'))return toast('Please choose a CSV file');if(file.size>10*1024*1024)return toast('CSV is larger than 10 MB');const raw=parseCsv(await file.text());if(!raw.rows.length)return toast('No transaction rows found');state.file=file;state.raw=raw;state.mapping=detectMapping(raw.headers);state.step=2;renderApp()}
function useSample(){const text=`Date,Description,Vendor,Debit,Credit,Category,Balance\n07/01/2026,Adobe Creative Cloud,ADOBE,64.99,,Software,18435.01\n07/02/2026,Customer payment,ACME CLIENT,,4250.00,Income,22685.01\n07/03/2026,Fuel purchase,SHELL 0421,186.42,,Fuel,22498.59\n07/03/2026,Fuel purchase,SHELL 0421,186.42,,Fuel,22312.17\n07/05/2026,Office supplies,AMZN MKTPLACE,242.18,,Office Supplies,22069.99\n07/06/2026,Electric utility,CITY ELECTRIC,584.10,,Utilities,21485.89\n07/08/2026,Payroll processing,GUSTO,8450.00,,Payroll,13035.89\n07/09/2026,Consulting revenue,NORTHSTAR LLC,,6200.00,Income,19235.89`;state.file={name:'sample-transactions.csv',size:text.length};state.raw=parseCsv(text);state.mapping=detectMapping(state.raw.headers);state.step=2;renderApp()}
function action(name){if(name==='sample')return useSample();if(name==='new-import'){state.view='imports';state.step=1;renderApp();return}if(name==='back'){state.step=Math.max(1,state.step-1);renderApp();return}if(name==='validate'){if(!state.mapping.date||!state.mapping.description||!state.mapping.amount)return toast('Map date, description, and amount');state.validation=validateTransactions(normalizeTransactions(state.raw.rows,state.mapping));state.step=3;renderApp();return}if(name==='preview'){state.step=4;renderApp();return}if(name==='commit'){const valid=state.validation.rows.filter(x=>x.valid);const s=state.validation.summary;saveImport({id:crypto.randomUUID(),filename:state.file?.name||'statement.csv',createdAt:new Date().toISOString(),rows:valid.length,validRate:Math.round((s.valid/s.total)*100),debits:s.debits,credits:s.credits},valid);state.step=5;renderApp();return}if(name==='another'){state.step=1;state.file=null;state.raw=null;state.mapping={};state.validation=null;renderApp();return}if(name==='view-history'){state.view='history';renderApp();return}if(name==='clear'){clearImports();renderApp();toast('Demo import data cleared');return}if(name==='save')toast('Import settings saved')}

state.user?renderApp():authScreen();
